// examples/angular-react-mfes/angular-in-react/wc-react-shell/src/app/app.tsx
import * as React from 'react';


import { Link } from 'react-router-dom';

import('wc_angular_remote/Module');

export function App() {
  return (
    <React.Suspense fallback={null}>
      <div style={{border: "2px dashed black"}}>
        <h1>This is a React Shell</h1>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
      </ul>
        <angular-mfe></angular-mfe>
      </div>
    </React.Suspense>
  );
}

export default App;

// examples/angular-react-mfes/react-in-angular/ng-shell/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NxWelcomeComponent } from './nx-welcome.component';

@Component({
  standalone: true,
  imports: [NxWelcomeComponent, RouterModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'wc-ng-shell';
}

<div style="border: 3px dashed black">
  <h1>This is an Angular Shell</h1>
  <ul class="remote-menu">
    <li><a routerLink="/">Home</a></li>
  </ul>

  <react-mfe></react-mfe>
</div>
